CU-23kvwh6 - Remove unused integrations
tul-ftims-students-council/DWFtims pull request #14
Opened 2022-03-06 20:13 UTC by mdzieciuchowicz

2022-03-06 20:13 UTC, pmakowski23 commented
Task linked: [CU-23kvwh6 Remove unused integrations](https://app.clickup.com/t/23kvwh6)

2022-03-06 20:19 UTC, pmakowski23 requested changes

2022-03-06 20:19 UTC, pmakowski23 commented on components/register-confirmation/register-confirmation.module.css
> +.register-confirmation-visual-wrapper {
This and some other CSS classes are unused and can be also removed 😉 Please leave only classes that are used in `.../register-confirmation.tsx`

2022-03-06 21:00 UTC, mdzieciuchowicz commented on components/register-confirmation/register-confirmation.module.css
> +.register-confirmation-visual-wrapper {
Fixed

2022-03-06 21:02 UTC, pmakowski23 approved these changes
Great work!

2022-03-07 17:25 UTC, pmakowski23 approved these changes
Wszystko git

2022-03-07 17:25 UTC, pmakowski23 commented on components/register-confirmation/register-confirmation.module.css
> +    margin: 30px 0;
Tutaj chyba jeszcze bardzije

2022-03-07 17:28 UTC, oskarkurczewski approved these changes

2022-03-07 17:28 UTC, merged