CU-25d7ac7 - Landing page animation
tul-ftims-students-council/DWFtims pull request #16
Opened 2022-03-19 15:04 UTC by novacooo

2022-03-19 15:04 UTC, pmakowski23 commented
Task linked: [CU-25d7ac7 Landing page animation](https://app.clickup.com/t/25d7ac7)

2022-03-19 15:12 UTC, pmakowski23 requested changes
Please resolve conflicts with `master` branch

2022-03-19 15:12 UTC, pmakowski23 commented on components/registration/form.module.css
> +  /* max-width: 400px; */
Please remove all comments

2022-03-19 15:12 UTC, pmakowski23 commented on .env.local.example
> -# If you’d like to enable GitHub OAuth, fill these below
Please don't remove this file

2022-03-19 15:39 UTC, stepniaczky approved these changes

2022-03-20 14:12 UTC, pmakowski23 approved these changes

2022-03-20 14:12 UTC, merged