Feature/cu 24p6rna
tul-ftims-students-council/DWFtims pull request #9
Opened 2022-02-27 21:47 UTC by UnderMan4

Changed schedule to Youtube stream chat on "Transmisja" page
live and chat is always taken from stage A

2022-02-27 21:47 UTC, pmakowski23 commented
Task linked: [CU-24p6rna Change schedule to youtube chat](https://app.clickup.com/t/24p6rna)

2022-02-27 22:41 UTC, pmakowski23 requested changes
And also empty `live-chat.module.css` is necessary. You can just move `live-chat.tsx` to `/stage/` as it is only being used there. 

Few cosmetic changes but other than that great job as chat is working and looking perfectly well 😀

2022-02-27 22:41 UTC, pmakowski23 commented on components/live/live-chat.tsx
> +const getStages = async (setLiveId: (s: any) => void) => {
You can remove this method as it is unused.

2022-02-27 22:41 UTC, pmakowski23 commented on components/live/live-chat.tsx
> +import styles from './live-chat.module.css';
Lines 2-4 are unused and can be removed

2022-02-27 22:41 UTC, pmakowski23 commented on components/live/live-chat.tsx
> +    console.log('id', liveId);
Please remove all console logs

2022-02-27 22:41 UTC, pmakowski23 commented on components/stage/stage-container.tsx
>  import ScheduleSidebar from '@components/schedule/schedule-sidebar';
this import can be removed

2022-02-27 22:41 UTC, pmakowski23 commented on components/stage/stage-container.tsx
> +              title="live"
The title is better dynamic

2022-02-27 22:41 UTC, pmakowski23 commented on components/stage/stage-container.tsx
> +  const updatedStage = updatedStages.find((s: Stage) => s.slug === 'a') || stage;
This shouldn't be changed, because If slug will be changed then I won't work

2022-02-27 22:41 UTC, pmakowski23 commented on components/stage/stage-container.tsx
> +      {/* <ScheduleSidebar allStages={updatedStages} /> */}
You can remove this unused component

2022-02-27 22:41 UTC, pmakowski23 commented on components/stage/stage-container.tsx
> +      <LiveChat liveId={updatedStage.stream.split('/')[4]} />
You can export that to variable to make it more readable

2022-02-28 10:28 UTC, pmakowski23 approved these changes
Great work!

2022-03-02 21:16 UTC, mdzieciuchowicz approved these changes

2022-03-02 21:16 UTC, merged